services:
  postgres-gateway:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${PG_GATEWAY_DB:-gateway}
      POSTGRES_USER: ${PG_GATEWAY_USER:-gateway}
      POSTGRES_PASSWORD: ${PG_GATEWAY_PASSWORD:-gateway_pass}
    volumes:
      - gateway_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_GATEWAY_USER:-gateway} -d ${PG_GATEWAY_DB:-gateway}"]
      interval: 5s
      timeout: 3s
      retries: 20

  api_gateway:
    build: .
    ports:
      - "8080:8080"
    environment:
      - HTTP_ADDR=:8080
      - FILE_STORING_HOST=${FILE_STORING_HOST:-host.docker.internal}
      - FILE_STORING_PORT=${FILE_STORING_PORT:-8082}
      - FILE_ANALYSIS_HOST=${FILE_ANALYSIS_HOST:-host.docker.internal}
      - FILE_ANALYSIS_PORT=${FILE_ANALYSIS_PORT:-8081}
      - PG_GATEWAY_DB=${PG_GATEWAY_DB:-gateway}
      - PG_GATEWAY_USER=${PG_GATEWAY_USER:-gateway}
      - PG_GATEWAY_PASSWORD=${PG_GATEWAY_PASSWORD:-gateway_pass}
      - PG_GATEWAY_HOST=postgres-gateway
      - PG_GATEWAY_PORT=5432
    depends_on:
      - postgres-gateway
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8088:8080"
    environment:
      - URL=/../api-files/openapi.yaml
    volumes:
        - ./openapi.yaml:/usr/share/nginx/html/openapi.yaml:ro

volumes:
  gateway_db_data:
