services:
  postgres-analysis:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${PG_ANALYSIS_DB:-analysis}
      POSTGRES_USER: ${PG_ANALYSIS_USER:-analysis}
      POSTGRES_PASSWORD: ${PG_ANALYSIS_PASSWORD:-analysis_pass}
    volumes:
      - analysis_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_ANALYSIS_USER:-analysis} -d ${PG_ANALYSIS_DB:-analysis}"]
      interval: 5s
      timeout: 3s
      retries: 20

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      # опционально, чтобы закрыть доступ ключом:
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY:-local-dev-key}
  analysis_service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - FILE_STORING_BASE_URL=http://158.160.208.12
      - FILE_STORING_PORT=8082
      - EMBEDDING_BASE_URL=http://158.160.208.12
      - EMBEDDING_PORT=8083
      - PG_ANALYSIS_DB=${PG_ANALYSIS_DB:-analysis}
      - PG_ANALYSIS_USER=${PG_ANALYSIS_USER:-analysis}
      - PG_ANALYSIS_PASSWORD=${PG_ANALYSIS_PASSWORD:-analysis_pass}
      - PG_ANALYSIS_HOST=postgres-analysis
      - PG_ANALYSIS_PORT=5432
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_GRPC_PORT=6334
      - QDRANT_COLLECTION=plagiarism_chunks_v1
      - QDRANT_VECTOR_SIZE=256
      - QDRANT_API_KEY=${QDRANT_API_KEY:-local-dev-key}
    depends_on:
      - postgres-analysis
      - qdrant

volumes:
  qdrant_storage:
  analysis_db_data:
